import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MODEL_TYPE = os.getenv('MODEL_TYPE')
MODEL_ID = os.getenv('MODEL_ID')
MAX_MODEL_TOKENS = os.getenv('MAX_MODEL_TOKENS')

TELEGRAM_AUTH_GROUP_ID = os.getenv('TELEGRAM_AUTH_GROUP_ID')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_BOT_ALIAS = os.getenv('TELEGRAM_BOT_ALIAS')
TELEGRAM_ADMIN_NICKNAME = os.getenv('TELEGRAM_ADMIN_NICKNAME', 'bot\'s admin')

RESPONSE_TIMEOUT = os.getenv('RESPONSE_TIMEOUT')